Remove context.TODO() from client_go method calls
openshift/cluster-monitoring-operator pull request #1240
Opened 2021-06-23 10:31 UTC by slashpai

As in title [MON-1251](https://issues.redhat.com/browse/MON-1251)

This is first PR to remove context.TODO() and replace with real context in tests

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

2021-06-23 13:02 UTC, jan--f requested changes
Just a nit, otherwise lgtm.

2021-06-23 13:07 UTC, slashpai commented on .gitignore
> +.idea
Thank you didn't know about it :) I have removed that commit

2021-06-23 15:22 UTC, dgrisonnet commented on test/e2e/framework/client.go
> +	ctx context.Context,
nit: let's be consistent and put the context parameter in second place after the client

2021-06-25 05:53 UTC, slashpai commented
/retest

2021-06-28 05:23 UTC, slashpai commented
/retest

2021-06-28 08:23 UTC, dgrisonnet commented
/lgtm

2021-06-28 09:48 UTC, merged