eo metrics for Telemetry
openshift/cluster-monitoring-operator pull request #1559
Opened 2022-02-14 15:43 UTC by pmoogi-redhat

This PR contains whitelisting of the elasticsearch-operator metrics for Telemetry captured in the below document:
  mentioned in this doc https://docs.google.com/document/d/1ek98QDTztWHuYzUX_T53O9JblUtL9-YRMUK5oHMIK8w/edit

- Changes done in manifests/0000_50_cluster-monitoring-operator_04-config.yaml to include the above metrics.
- Reference https://issues.redhat.com/browse/LOG-2202 [JIRA ticket for implementing EO Metrics]
- Reference https://issues.redhat.com/browse/LOG-1852 [for selecting EO metrics for Telemetry]
- https://github.com/openshift/elasticsearch-operator/blob/master/internal/metrics/metrics.go [EO Metrics implementation]

2022-02-15 14:17 UTC, pmoogi-redhat commented
@jan--f kindly review this PR.

2022-02-25 09:09 UTC, anpingli commented
/test e2e-aws-single-node

2022-03-01 09:20 UTC, jan--f commented
/lgtm
/label docs-approved
cc @sferich888 for px approval
cc @juzhao @lihongyan1 for qe approval
@pmoogi-redhat please note that telemeter ingestion will require allow-listing on the telemeter side as well as detailed in point 6 in https://docs.google.com/document/d/1a6n5iBGM2QaIQRg9Lw4-Npj6QY9--Hpx3XYut-BrUSY/edit#heading=h.i05nm4wmvn7x

2022-03-01 09:36 UTC, PhilipGough commented
/skip

2022-03-01 09:36 UTC, PhilipGough approved these changes

2022-03-01 09:46 UTC, juzhao commented on Documentation/data-collection.md
> +    - '{__name__="cluster:eo_es_documents_created_total:sum"}'
two `cluster:eo_es_documents_created_total:sum` in this file

2022-03-01 09:51 UTC, juzhao commented on Documentation/data-collection.md
> +    # Number of clusters with misconfigured cpu or memory resources across the fleet.
it seems the metric is only for memory, does not include cpu

2022-03-01 09:53 UTC, juzhao commented on Documentation/sample-metrics.md
> +{__name__=~"cluster:usage:.*|count:up0|count:up1|cluster_version|cluster_version_available_updates|cluster_operator_up|cluster_operator_conditions|cluster_version_payload|cluster_installer|cluster_in
two `cluster:eo_es_documents_created_total:sum` in this file

2022-03-01 09:53 UTC, juzhao commented on Documentation/telemetry/telemeter_query
> +{__name__=~"cluster:usage:.*|count:up0|count:up1|cluster_version|cluster_version_available_updates|cluster_operator_up|cluster_operator_conditions|cluster_version_payload|cluster_installer|cluster_in
two `cluster:eo_es_documents_created_total:sum` in this file

2022-03-01 10:02 UTC, jan--f commented
/hold
@pmoogi-redhat please address @juzhao review comments.

2022-03-23 04:56 UTC, pmoogi-redhat commented
@jan--f @juzhao addressed a duplicate metric issue in the whitelisting metrics manifest.

2022-05-13 09:09 UTC, pmoogi-redhat commented
@juzhao  addressed your review comments. kindly check. thank you.

2022-05-13 12:34 UTC, juzhao commented on Documentation/data-collection.md
> +    - '{__name__="eo_es_misconfigured_memory_resources_info"}'
it seems the metric is only for memory, does not include cpu

2022-05-13 12:34 UTC, juzhao commented on manifests/0000_50_cluster-monitoring-operator_04-config.yaml
> +    - '{__name__="eo_es_misconfigured_memory_resources_info"}'
it seems the metric is only for memory, does not include cpu

2022-05-13 12:35 UTC, juzhao commented
just one comment, others are LGTM

2022-05-13 13:43 UTC, jan--f requested changes

2022-05-13 13:43 UTC, jan--f commented on manifests/0000_50_cluster-monitoring-operator_04-config.yaml
> +    # Number of clusters with misconfigured cpu or memory resources across the fleet.
```suggestion
    # Number of clusters with misconfigured memory resources across the fleet.
```

2022-05-17 02:46 UTC, juzhao commented on Documentation/data-collection.md
> +    - '{__name__="eo_es_misconfigured_memory_resources_info"}'
@jan--f this should also be updated

2022-05-18 11:26 UTC, jan--f commented
/lgtm
/label docs-approved
/label px-approved
Adding labels because a telemetry addition has no user or doc impact.
Ping @juzhao for qe-approved.

2022-05-18 11:29 UTC, jan--f commented
/lgtm cancel
Sorry I failed to notice that the generate job still fails.

2022-05-19 12:15 UTC, jan--f commented
/lgtm

2022-05-23 16:03 UTC, jan--f commented
/unhold

2022-05-23 20:44 UTC, merged