Create a patch im CMO for NodeClockNotSynchronising
openshift/cluster-monitoring-operator pull request #1604
Opened 2022-03-21 18:16 UTC by lnguyen1401

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

The runbook PR: https://github.com/openshift/runbooks/pull/36/files
The related Jira card: https://issues.redhat.com/browse/OSD-8737

2022-03-21 20:15 UTC, lnguyen1401 commented
/retest

2022-03-21 20:48 UTC, lnguyen1401 commented
/retest

2022-03-22 13:59 UTC, lnguyen1401 commented
/retest

2022-03-22 16:19 UTC, simonpasquier commented
/hold

We need https://github.com/openshift/runbooks/pull/36 to be merged first.
We'd need a formal agreement from @openshift/teams/sre-alert-sme that increasing the severity to `critical` is ok. Once it's approved, the alerting rule should be patched in [jsonnet/utils/sanitize-rules.libsonnet](https://github.com/openshift/cluster-monitoring-operator/blob/843ca82c018431b95dcfdd6c32bf734d8f53319b/jsonnet/utils/sanitize-rules.libsonnet#L121)

2022-03-22 17:36 UTC, lnguyen1401 commented
> /hold
> 
> We need [openshift/runbooks#36](https://github.com/openshift/runbooks/pull/36) to be merged first. We'd need a formal agreement from @openshift/teams/sre-alert-sme that increasing the severity to `critical` is ok. Once it's approved, the alerting rule should be patched in [jsonnet/utils/sanitize-rules.libsonnet](https://github.com/openshift/cluster-monitoring-operator/blob/843ca82c018431b95dcfdd6c32bf734d8f53319b/jsonnet/utils/sanitize-rules.libsonnet#L121)

2022-03-22 18:02 UTC, lnguyen1401 commented
Hello @simonpasquier , do you have an SOP to create a formal agreement ?

2022-04-04 15:00 UTC, fahlmant commented
@simonpasquier We have agreement. What's the process to "formal" agreement here?

2022-05-13 17:50 UTC, lnguyen1401 commented
/retest

2022-05-13 18:00 UTC, lnguyen1401 commented
hello @simonpasquier , the run book has been merged. i made a patch for NodeClockNotSynchronising in jsonnet/utils/sanitize-rules.libsonnet

2022-05-17 15:38 UTC, lnguyen1401 commented
/retest

2022-05-19 15:21 UTC, lnguyen1401 commented
/retest

2022-06-03 10:47 UTC, boranx reviewed
/lgtm

Looks like the change is straightforward, anything blocking us from merging this?

2022-06-03 16:08 UTC, ritmun commented
/assign @bparees

2022-06-04 18:36 UTC, bparees commented
/unassign
/assign @jan--f

2022-06-09 20:40 UTC, ritmun commented
I'm not sure what the assignment needs to be. I followed this message posted by CI bot
 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/87340776/172940308-293b9eb6-785b-435b-94cc-7c49591e6a26.png">

2022-06-10 07:12 UTC, jan--f requested changes

2022-06-10 07:12 UTC, jan--f commented on jsonnet/utils/sanitize-rules.libsonnet
> +      },
This jsonnet snippet doesn't have any effect, the ClockNotSynced alert is in the `node-exporter` group. You need something like this (with probably better formatting):
```suggestion
    ],
  },
  {
    name: 'node-exporter',
    rules: [
      {
        alert: 'NodeClockNotSynchronising',
        labels: {
          severity: 'critical',
        },
      },
```

2022-06-10 18:13 UTC, lnguyen1401 commented
/retest

2022-06-13 13:11 UTC, lnguyen1401 commented
/retest

2022-06-13 13:56 UTC, simonpasquier commented
/skip

2022-06-13 13:58 UTC, simonpasquier commented
/hold cancel
/lgtm

2022-06-13 14:08 UTC, simonpasquier commented
/retitle Bug 2096315: Create a patch im CMO for NodeClockNotSynchronising

2022-06-13 14:15 UTC, merged