Add odf_system_objects_total and odf_system_bucket_count
openshift/cluster-monitoring-operator pull request #1763
Opened 2022-09-07 12:26 UTC by weirdwiz

This commit adds two new metrics for object and bucket count, this
further deprecates the Noobaa metrics for the same.

Jira Issue: https://issues.redhat.com/browse/RHSTOR-3473

2022-09-08 07:55 UTC, agarwal-mudit commented
/ok-to-test

2022-09-09 09:53 UTC, weirdwiz commented
PTAL @simonpasquier

2022-09-12 14:40 UTC, jan--f commented
I'm afraid the label sets of these metrics are unsuitable to ship to telemetry. Given these definitions:
```
    - expr: |
        sum by (namespace, managedBy, job, service) (ocs_objectbucket_objects_total)
      labels:
        system_type: OCS
        system_vendor: Red Hat
      record: odf_system_objects_total
    - expr: |
        ocs_objectbucket_count_total
      labels:
        system_type: OCS
        system_vendor: Red Hat
      record: odf_system_bucket_count
```
this would ship two unneeded (I assume) labels to telemetry (`system_type` and `system_vendor`).
Also the label set of `odf_system_objects_total` seems to have the potential to create an unbounded value set.
You'll need convincing arguments why you need all these labels in telemetry.

2022-09-12 16:25 UTC, weirdwiz commented
@jan--f the other `odf_system` metrics contain the same labels `system_type` and `system_vendor`.

The labels for `odf_system_objects_total`, only have a few possible values as the operator is only installed in one namespace, and the value of managedBy, job, and service will only have fixed values per operator. But we can reduce the label set to just `job`.

wdyt @mulbc

2022-09-13 09:24 UTC, simonpasquier commented
If the system_type and system_vendor values are fixed, we could even add them as additional selectors to the telemeter config which would avoid any risk of shipping unwanted metrics:

```
- '{__name__="odf_system_objects_total",system_type="OCS",system_vendor="Red Hat"}'
- '{__name__="odf_system_bucket_count",system_type="OCS",system_vendor="Red Hat"}'
``` 

> The labels for odf_system_objects_total, only have a few possible values as the operator is only installed in one namespace, and the value of managedBy, job, and service will only have fixed values per operator. But we can reduce the label set to just job.

What if the odf_system_objects_total and odf_system_bucket_count recording rules selected exactly that namespace? E.g. assuming that the namespace is openshift-storage

```
sum (ocs_objectbucket_objects_total{namespace="openshift-storage"})
```

2022-09-13 09:46 UTC, mulbc commented
@weirdwiz - please implement what @simonpasquier suggested, it's fine by me

in the ocs-operator and noobaa code you use `sum by (namespace, job, service)` or `sum by (namespace, managedBy, job, service)` - please just remove the by-clause so that is reads 

```
sum (ocs_objectbucket_objects_total)
      labels:
        system_type: OCS
        system_vendor: Red Hat
      record: odf_system_objects_total
```

for example
As discussed with @jan--f this will allow them to accept this PR

2022-09-13 09:49 UTC, jan--f requested changes
Lets also add the additional guarding for the static label values that Simon suggested.

2022-09-13 09:49 UTC, jan--f commented on Documentation/data-collection.md
> +    - '{__name__="odf_system_bucket_count"}'
```suggestion
    - '{__name__="odf_system_bucket_count",system_type="OCS",system_vendor="Red Hat"}'
```

2022-09-13 09:49 UTC, jan--f commented on Documentation/data-collection.md
> +    - '{__name__="odf_system_objects_total"}'
```suggestion
    - '{__name__="odf_system_objects_total",system_type="OCS",system_vendor="Red Hat"}'
```

2022-09-13 10:54 UTC, weirdwiz commented
PR up for OCS and Noobaa Mixins. 

https://github.com/red-hat-storage/ocs-operator/pull/1802
https://github.com/noobaa/noobaa-mixins/pull/30

2022-09-13 13:23 UTC, jan--f commented
/label docs-approved
/label px-approved
/label qe-approved
Adding labels for a telemetry addition.

2022-09-13 15:22 UTC, weirdwiz commented
@jan--f all the downstream PRs are merged now.

2022-09-13 15:58 UTC, jan--f commented
/lgtm

2022-09-13 15:58 UTC, jan--f commented
/retest

2022-09-13 19:37 UTC, merged