OCPBUGS-7282: Node Exporter ignores network interface under name "cali[a-f0-9]*"
openshift/cluster-monitoring-operator pull request #1905
Opened 2023-02-28 09:56 UTC by raptorsun

* [x] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

This PR resolves https://issues.redhat.com/browse/OCPBUGS-7282 .
The issue is similar to https://issues.redhat.com/browse/OCPBUGS-2729 .

2023-02-28 10:22 UTC, raptorsun commented
/jira refresh

2023-02-28 12:33 UTC, raptorsun commented
/test e2e-agnostic-operator

2023-02-28 13:30 UTC, raptorsun commented
/jira refresh

2023-02-28 14:55 UTC, jan--f commented
/jira refresh

2023-02-28 14:56 UTC, jan--f requested changes
Only the changelog needs an update. Otherwise :+1:

2023-02-28 14:56 UTC, jan--f commented on CHANGELOG.md
> +- [#xxxx](https://github.com/openshift/cluster-monitoring-operator/pull/xxxx) Node Exporter ignores network interface under name "cali[a-f0-9]*".
```suggestion
- [#1905](https://github.com/openshift/cluster-monitoring-operator/pull/1905) Node Exporter ignores network interface under name "cali[a-f0-9]*".
```

2023-02-28 14:57 UTC, jan--f commented
/jira refresh

2023-02-28 15:30 UTC, simonpasquier commented on jsonnet/main.jsonnet
>          // thus [a-z0-9]{15}}
```suggestion
        // thus [a-z0-9]{15}
```

2023-02-28 17:05 UTC, raptorsun commented
Thanks for the review @jan--f @simonpasquier  :) 
I have removed the entry in the change log alongside the correction on the typo since it is tracked in JIRA already.

2023-02-28 19:35 UTC, raptorsun commented
/test e2e-agnostic

2023-03-02 02:38 UTC, juzhao commented
@raptorsun launched bot cluster with PR
`launch openshift/cluster-monitoring-operator#1905 gcp`
but did not see `collector.netclass.ignored-devices` and `collector.netdev.device-exclude` settings in node-exporter, full info see: http://pastebin.test.redhat.com/1093428

and checked in 4.13.0-0.nightly-2023-02-27-101545, there is `collector.netclass.ignored-devices` setting
see from: http://pastebin.test.redhat.com/1093429

2023-03-02 09:44 UTC, raptorsun commented
> 



> @raptorsun launched bot cluster with PR `launch openshift/cluster-monitoring-operator#1905 gcp` no configuration for node-exporter, did not see `collector.netclass.ignored-devices` and `collector.netdev.device-exclude` settings in node-exporter, full info see: http://pastebin.test.redhat.com/1093428
> 
> and checked in 4.13.0-0.nightly-2023-02-27-101545, no configuration for node-exporter, there is `collector.netclass.ignored-devices` setting see from: http://pastebin.test.redhat.com/1093429
> 
> after disabled netdev/netclass on bot cluster, would see `collector.netclass.ignored-devices` and `collector.netdev.device-exclude` settings in node-exporter, since OCPBUGS-7282 is filed on 4.12, disable netdev/netclass is not supported then, I don't think we should disable netdev/netclass
> 
> ```
> $ oc -n openshift-monitoring get ds node-exporter -oyaml | grep collector
>         - --no-collector.wifi
>         - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|run/k3s/containerd/.+|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
>         - --collector.netclass.ignored-devices=^(veth.*|[a-f0-9]{15}|enP.*|ovn-k8s-mp[0-9]*|br-ex|br-int|br-ext|br[0-9]*|tun[0-9]*|cali[a-f0-9]*)$
>         - --collector.netdev.device-exclude=^(veth.*|[a-f0-9]{15}|enP.*|ovn-k8s-mp[0-9]*|br-ex|br-int|br-ext|br[0-9]*|tun[0-9]*|cali[a-f0-9]*)$
>         - --collector.cpu.info
>         - --collector.textfile.directory=/var/node_exporter/textfile
>         - --no-collector.cpufreq
>         - --no-collector.tcpstat
>         - --no-collector.netdev
>         - --no-collector.netclass
>         - --no-collector.buddyinfo
>         - '[[ ! -d /node_exporter/collectors/init ]] || find /node_exporter/collectors/init
> ```

Thank you for raising the issue.
I created [a ticket for this bug](https://issues.redhat.com/browse/OCPBUGS-8215) and will create a patch soon.

2023-03-02 10:46 UTC, raptorsun commented
https://github.com/openshift/cluster-monitoring-operator/pull/1909

Hello @juzhao , the bug fix has been created :) 
It would be great if we can merge it before code freeze.

2023-03-03 02:58 UTC, juzhao commented
issue is fixed, details see from bug comment
/label qe-approved

2023-03-07 13:55 UTC, simonpasquier commented
/hold

waiting for https://github.com/openshift/cluster-monitoring-operator/pull/1909

2023-03-16 07:46 UTC, simonpasquier reviewed
/lgtm
/hold cancel

2023-03-16 10:12 UTC, merged

2023-03-29 06:28 UTC, raptorsun commented
/cherry-pick release-4.13