MON-4046: add early validation for Platform and UWM monitoring configmaps
openshift/cluster-monitoring-operator pull request #2490
Opened 2024-10-03 08:15 UTC by machine424

This is done through validation webhooks.

An opt-out mechansim is provided to make the configmaps skip CMO's
validate webhook in case.

The exposed validate webhook path has no auth for now.

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

2024-10-03 14:25 UTC, machine424 commented on pkg/server/server.go
> +	server.Handler.NonGoRestfulMux.HandleFunc("/admission-monitoringconfigmaps/validate", func(w http.ResponseWriter, r *http.Request) {
https://github.com/openshift/cluster-monitoring-operator/blob/8319fc2d5eaa36929e28e261337a78e7dab39920/manifests/0000_50_cluster-monitoring-operator_03-service.yaml#L10

2024-10-03 15:11 UTC, machine424 commented on pkg/configvalidate/configvalidate.go
> +		_, err := manifests.NewUserConfigFromString(s)
check if it's strict: duplicated fields? unknwon fields? etc

2024-10-06 19:47 UTC, machine424 commented on pkg/manifests/config.go
> +	// TODO: say unknwon not fallged currenttly.
release notes

2024-10-06 19:47 UTC, machine424 commented on pkg/server/server.go
> +		// TODO: explain why
todo

2024-10-06 19:47 UTC, machine424 commented on test/e2e/config_test.go
> +	// TODO: maybe check error type
todo

2024-10-06 19:47 UTC, machine424 commented on pkg/configvalidate/configvalidate.go
> +	// TODO: make sure collectionProfilesEnabled doesn't change
todo

2024-10-06 19:47 UTC, machine424 commented on test/e2e/user_workload_monitoring_test.go
> +// TODO: adapt
todo

2024-10-07 08:26 UTC, machine424 commented on pkg/manifests/manifests_test.go
> -  image: quay.io/test/prometheus-operator
thanks to the new `UnmarshalStrict`

2024-10-08 10:35 UTC, machine424 commented
/retest-required

2024-10-30 13:46 UTC, machine424 commented
/retest-required

2024-11-14 08:28 UTC, machine424 commented
/retest-required

2024-11-14 11:42 UTC, machine424 commented
/retest-required

2024-11-18 10:23 UTC, jan--f requested changes
Just a nit to fix a comment typo. Otherwise this lgtm!

2024-11-18 10:23 UTC, jan--f commented on pkg/server/server.go
> +	// Following tge fail-early paradigm makes configuration failures easily detectable by users.
```suggestion
	// Following the fail-early paradigm this makes configuration failures easily detectable by users.
```

2024-11-19 12:08 UTC, machine424 commented
/retest-required

2024-11-20 09:39 UTC, jan--f commented
/lgtm
I'll give @simonpasquier a chance to take a look too so
/hold
feel free to unhold

2024-11-20 09:54 UTC, machine424 commented
/label acknowledge-critical-fixes-only

2024-11-21 19:57 UTC, machine424 commented
/unhold

2024-11-22 02:01 UTC, merged